<?php


namespace Nemundo\Abrechnung\Template;


use Nemundo\Abrechnung\Com\Navigation\AbrechnungNavigation;
use Nemundo\Com\Template\AbstractTemplateDocument;

class AbrechnungTemplate extends AbstractTemplateDocument
{

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        new AbrechnungNavigation($this);

    }

}