<?php

namespace Nemundo\Abrechnung\Page;


use Nemundo\Abrechnung\Com\Navigation\AbrechnungNavigation;
use Nemundo\Abrechnung\Content\Abrechnung\AbrechnungContentType;
use Nemundo\Abrechnung\Data\Abrechnung\AbrechnungForm;
use Nemundo\Abrechnung\Data\Abrechnung\AbrechnungReader;
use Nemundo\Abrechnung\Parameter\AbrechnungParameter;
use Nemundo\Abrechnung\Site\JournalSite;

use Nemundo\Abrechnung\Template\AbrechnungTemplate;
use Nemundo\Admin\Com\Table\AdminClickableTable;
use Nemundo\Admin\Com\Widget\AdminWidget;
use Nemundo\Package\Bootstrap\Layout\BootstrapTwoColumnLayout;
use Nemundo\Package\Bootstrap\Table\BootstrapClickableTableRow;

class AbrechnungPage extends AbrechnungTemplate
{

    public function getContent()
    {

        $layout = new BootstrapTwoColumnLayout($this);

        $table = new AdminClickableTable($layout->col1);

        $abrechnungReader = new AbrechnungReader();
        $abrechnungReader->model->loadGroup();

        foreach ($abrechnungReader->getData() as $abrechnungRow) {


            $row = new BootstrapClickableTableRow($table);
            $row->addText($abrechnungRow->abrechnung);
            $row->addText($abrechnungRow->group->group);

            $site = clone(JournalSite::$site);
            $site->addParameter(new AbrechnungParameter($abrechnungRow->id));
            $row->addClickableSite($site);


        }


        $widget = new AdminWidget($layout->col2);
        $widget->widgetTitle = 'Neue Abrechnung';

       // $form = new AbrechnungForm($widget);

        $type=new AbrechnungContentType();
        $type->gr
        $type->getForm($widget);


        return parent::getContent(); // TODO: Change the autogenerated stub

    }

}