<?php

namespace Nemundo\Abrechnung\Layout;


use Nemundo\Abrechnung\Com\Navigation\AbrechnungNavigation;
use Nemundo\Abrechnung\Com\Table\JournalTable;
use Nemundo\Abrechnung\Parameter\AbrechnungParameter;
use Nemundo\Html\Container\AbstractContainer;
use Nemundo\Html\Container\AbstractHtmlContainer;
use Nemundo\Package\Bootstrap\Layout\BootstrapTwoColumnLayout;

// evtl. AdminLayout

class AbrechnungLayout extends AbstractHtmlContainer  // BootstrapTwoColumnLayout
{

    /**
     * @var BootstrapTwoColumnLayout
     */
    private $layout;

    protected function loadContainer()
    {

        parent::loadContainer(); // TODO: Change the autogenerated stub

        $nav = new AbrechnungNavigation();
        parent::addContainer($nav);

        $this->layout = new BootstrapTwoColumnLayout();
        parent::addContainer($this->layout);

        //$table = new JournalTable($this->layout->col1);
        //$table->abrechnungId = (new AbrechnungParameter())->getValue();  // $abrechnungId;


    }


    public function addContainer(AbstractContainer $container)
    {
        $this->layout->col2->addContainer($container);
    }

}